### ISSUE TITLE
Could not find symbol 'f0r_update' in loaded module (uvmap) (1.7)

### ISSUE THREAD

**Issue by sgyotk** [dyne/frei0r#103]
Happened with ffmpeg compiled on osx and ubuntu both.

Any ideas?

**Comment by jaromil** [comment]
This needs updating to 1_2 spec:

Effects of type `F0R_PLUGIN_TYPE_MIXER2` or `F0R_PLUGIN_TYPE_MIXER3` must provide the new f0r_update2 method.

**Comment by jaromil** [comment]
this was fixed some time ago

**Comment by sgyotk** [comment]
it is still not working in 2.3.0 with uvmap, I checked on osx
